project:
  type: website
  output-dir: docs

website:
  title: ""
  navbar:
    pinned: true
    left:
      - text: "Victor Hernandez Martinez"
        href: "#top"
      - text: CV
        href: "#top"
      - text: Research
        href: "#research"
      - text: Policy
        href: "#policy"
      - text: Teaching
        href: "#teaching"
    search: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    smooth-scroll: true
    link-external-newwindow: true
    grid:
      body-width: 1180px
      margin-width: 0px
      gutter-width: 1.25rem