project:
  type: website
  output-dir: docs

website:
  title: ""
  navbar:
    title: "Victor Hernandez Martinez"
    logo-href: "#top"
    pinned: true
    search: false
    left:
      - text: "CV"
        href: files/Victor_Hernandez_Martinez_CV.pdf
        target: _blank
      - text: "Research"
        href: "#research"
      - text: "Policy"
        href: "#policy"
      - text: "Teaching"
        href: "#teaching"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    smooth-scroll: true
    link-external-newwindow: true